version: '3.3'
name: polar-network-4
services:
  backend1:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: polarlightning/bitcoind:27.0
    container_name: polar-n4-backend1
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  alice:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/lnd:0.18.2-beta
    container_name: polar-n4-alice
    hostname: alice
    command: >-
      lnd --noseedbackup --debuglevel=debug --trickledelay=5000 --alias=alice
      --externalip=alice --tlsextradomain=alice --tlsextradomain=polar-n4-alice
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n4-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n4-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n4-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8081:8080'
      - '10001:10009'
      - '9735:9735'
  bob:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/lnd:0.18.2-beta
    container_name: polar-n4-bob
    hostname: bob
    command: >-
      lnd --noseedbackup --debuglevel=debug --trickledelay=5000 --alias=bob
      --externalip=bob --tlsextradomain=bob --tlsextradomain=polar-n4-bob
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n4-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n4-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n4-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/bob:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10002:10009'
      - '9736:9735'
  carol:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/lnd:0.18.2-beta
    container_name: polar-n4-carol
    hostname: carol
    command: >-
      lnd --noseedbackup --debuglevel=debug --trickledelay=5000 --alias=carol
      --externalip=carol --tlsextradomain=carol --tlsextradomain=polar-n4-carol
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n4-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n4-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n4-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10003:10009'
      - '9737:9735'
  alice-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/tapd:0.4.1-alpha
    container_name: polar-n4-alice-tap
    hostname: alice-tap
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=alice-tap
      --tlsextradomain=polar-n4-alice-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=polar-n4-alice:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access=rw
      --universe.sync-all-assets
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/tap/.lnd
      - ./volumes/tapd/alice-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8289:8089'
      - '12029:10029'
  bob-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/tapd:0.4.1-alpha
    container_name: polar-n4-bob-tap
    hostname: bob-tap
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=bob-tap
      --tlsextradomain=polar-n4-bob-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=polar-n4-bob:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access=rw
      --universe.sync-all-assets
    restart: always
    volumes:
      - ./volumes/lnd/bob:/home/tap/.lnd
      - ./volumes/tapd/bob-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8290:8089'
      - '12030:10029'
  carol-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 30s
    image: polarlightning/tapd:0.4.1-alpha
    container_name: polar-n4-carol-tap
    hostname: carol-tap
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=carol-tap
      --tlsextradomain=polar-n4-carol-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=polar-n4-carol:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access=rw
      --universe.sync-all-assets
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/tap/.lnd
      - ./volumes/tapd/carol-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8291:8089'
      - '12031:10029'
